name: shiron
description: A fashionable retail app
version: 2022.11.27+1016

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_breakpoints: ^0.1.1
  animations: ^2.0.2
  collection: ^1.16.0
  flutter_staggered_grid_view: ^0.6.1
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true